### ISSUE TITLE
Create ProjecHub Mockups

### ISSUE THREAD

**Issue by cableredi** [wwcodecolorado/returnship-project-voting#1]

**Comment by cableredi** [comment]
![excalidraw-2020331133422](https://user-images.githubusercontent.com/55605768/79279072-7010be00-7e6a-11ea-9030-804ea21b2df1.png)

**Comment by CodeMeKathy** [comment]
# Updated Mockups

![Landing Page](https://user-images.githubusercontent.com/32943879/85621523-6b6b4180-b633-11ea-8970-b8b0c1581de8.png)
![Project Details Page](https://user-images.githubusercontent.com/32943879/85621526-6c9c6e80-b633-11ea-9d80-31ca5aaabb9c.png)
![Projects Page](https://user-images.githubusercontent.com/32943879/85621530-6e663200-b633-11ea-903b-173852785290.png)
![Sign-Up Page](https://user-images.githubusercontent.com/32943879/85621532-6f975f00-b633-11ea-9ff6-900170019ea2.png)
![Vote Page](https://user-images.githubusercontent.com/32943879/85621535-70c88c00-b633-11ea-9c53-7692ecb408da.png)
![Admin - Landing](https://user-images.githubusercontent.com/32943879/85621513-66a68d80-b633-11ea-8aca-68a1b0e5feeb.png)
![Admin - Project Details](https://user-images.githubusercontent.com/32943879/85621519-69a17e00-b633-11ea-9b4d-6ed094ca6405.png)
